# Generated by Django 5.2.8 on 2025-11-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_product_networknode'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='level',
            field=models.IntegerField(choices=[(0, 'Factory'), (1, 'Retail Network'), (2, 'Individual Entrepreneur')], default=0, editable=False),
            preserve_default=False,
        ),
    ]
