# Generated by Django 5.2.8 on 2025-11-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_networknode_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networknode',
            name='level',
        ),
    ]
